name: Track UPS Packages

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          # Write credentials directly to file
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          
          # Run test script to verify credentials
          python test_credentials.py

      - name: Run tracking script
        env:
          UPS_CLIENT_ID: ${{ secrets.UPS_CLIENT_ID }}
          UPS_CLIENT_SECRET: ${{ secrets.UPS_CLIENT_SECRET }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
          ORIGIN_CITY: ${{ secrets.ORIGIN_CITY }}
          ORIGIN_STATE: ${{ secrets.ORIGIN_STATE }}
          ORIGIN_ZIP: ${{ secrets.ORIGIN_ZIP }}
        run: python updated_track_packages.py